FROM ubuntu:latest
RUN apt update -y && apt upgrade -y
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
RUN pip3 install django -y
RUN pip3 install django-crispy-forms -y
RUN apt-get install python3-dev -y
RUN apt install mariadb-client -y
RUN pip3 install mysqlclient -y
 