FROM ubuntu:latest
RUN sudo apt update && sudo apt upgrade
RUN sudo apt-get install python3
RUN sudo apt-get install python3-pip
RUN pip3 install django
RUN pip3 install django-crispy-forms
RUN sudo apt-get install python3-dev
RUN sudo apt install mariadb-client
RUN pip3 install mysqlclient
 